migrations/1683047918926_mime-type-counts.ts
migrations/1683061444855_sat-rarity-counts.ts
migrations/1683130423352_inscription-count.ts
migrations/1683130430977_chain-tip-view.ts
package-lock.json
package.json
src/api/util/helpers.ts
src/chainhook/helpers.ts
src/chainhook/schemas.ts
src/pg/helpers.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/cache.test.ts
tests/helpers.ts
tests/inscriptions.test.ts
tests/sats.test.ts
tests/server.test.ts
tests/status.test.ts

* Move chain tip and global inscription count to materialized views
* Unify all inscription updates under a postgres transaction
* Fix tests and create test chainhook message builder

fix: cache inscription counts for mime_type and sat_rarity

---

src/api/routes/inscriptions.ts
src/api/schemas.ts
src/api/util/helpers.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/inscriptions.test.ts

feat: add endpoint to retrieve all inscription transfers per block

---

src/pg/helpers.ts
src/pg/pg-store.ts
tests/inscriptions.test.ts

Also, fix gap logging false-positive

fix: use materialized view total count correctly

---

.github/workflows/vercel.yml

Now updates Vercel workflow to run after a release is published rather than when a commit is pushed to the `master` branch.

ci: update docs on release

---

.github/workflows/vercel.yml
migrations/1685378650151_prev-location.ts
migrations/1686170300438_curse-type.ts
src/api/routes/sats.ts
src/api/routes/status.ts
src/api/schemas.ts
src/api/util/helpers.ts
src/chainhook/schemas.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/helpers.ts
tests/inscriptions.test.ts
tests/sats.test.ts
tests/status.test.ts

* Keep `prev_output` and `prev_offset` in the locations table so we can calculate gaps
* Add `/sats/:ordinal/inscriptions` endpoint to list all cursed inscriptions for a single sat
* Support new chainhook event `cursed_inscription_revealed`
* Save and expose `curse_type` on all endpoints

feat: support cursed inscriptions

---

.github/workflows/ci.yml
jest.config.js

This PR adds Codecov to the Ordinals API. I've tested locally and the reports seem to be correct. I believe we can try this out to see how flaky it behaves and we can decide if we want to change it later.
Fixes #96

build: add codecov

---

src/pg/pg-store.ts

Previous code did not handle the empty `NODE_ENV` case correctly

fix: check for prod correctly when refreshing materialized views

---

src/chainhook/server.ts

I will reflect the change in the Chainhooks client as well (this API version does not use it yet)

fix: send 500 code if payload ingestion fails

---

src/chainhook/schemas.ts
src/chainhook/server.ts
src/env.ts
src/pg/pg-store.ts
tests/helpers.ts
tests/inscriptions.test.ts
tests/server.test.ts

This PR skips expensive inscription count materialized views when the chainhook node is not streaming new blocks (i.e. not caught up to chain tip) so we can have faster data replays. A future PR would reflect this change in the status endpoint so it doesn't show it as "ready" if it's not streaming.
Also, this PR adds an ENV that will allow us to skip automatic predicate registrations so we can run things manually if we need to.

fix: skip expensive view refreshes when not streaming new blocks

---

src/chainhook/schemas.ts
src/pg/pg-store.ts
tests/cache.test.ts
tests/inscriptions.test.ts

Calculate genesis location preemptively to get sat ordinal information

fix: remove inscription_number and ordinal_number from transfers

---

src/pg/helpers.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/inscriptions.test.ts

This will buy us time to look for a real solution (combination of materialized views, etc.)

fix: mark intractable `/inscriptions` result counts as 0 to avoid DB bottlenecks

---

migrations/1676395230930_inscriptions.ts
src/api/util/cache.ts
src/pg/pg-store.ts
tests/cache.test.ts

fix: make etag calculation sensitive to inscription location gap fills and upserts

---

src/pg/pg-store.ts
tests/inscriptions.test.ts

Adds secondary sorting by number for sort options that are not granular to individual inscriptions (genesis block height and sat rarity)
---

fix: add secondary sorting by inscription number

---

migrations/1692132685000_brc20-supply-view.ts
migrations/1692188000000_brc20-deploys-ticker-index.ts
src/api/schemas.ts
src/api/util/helpers.ts
src/pg/brc20/brc20-pg-store.ts
src/pg/brc20/types.ts
src/pg/helpers.ts
src/pg/pg-store.ts
tests/brc20.test.ts

So far commits are conventional and can be rebased.
- closes #159 
- adds `ticker_lower` ~`char(4)`~ `text` generated column to reduce total scan of `LOWER(ticker)` queries
- adds minted supplies materialized view (for token endpoints)
- adds deploy timestamp to token endpoints
- changes brc-20 ticker filter to prefix search instead of exact matches
- minor refactors
---

feat: add more brc20 features

---

src/admin-rpc/init.ts
src/env.ts
src/index.ts
src/pg/brc20/brc20-pg-store.ts
src/pg/brc20/helpers.ts
src/pg/brc20/types.ts
src/pg/counts/counts-pg-store.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/brc20.test.ts

* Batch inscription inserts so they are all inserted in one query per block, plus as few queries as possible when doing other calculations (location pointers, count accumulation, etc.)
* Separate BRC-20 processing into another process detached from block ingestion so we can trigger externally
* Create Admin RPC to quickly trigger a BRC-20 re-scan

fix: optimize inscription and brc-20 inserts

---

migrations/1694797181616_brc20-counts-by-address-event.ts
src/api/util/helpers.ts
src/pg/brc20/brc20-pg-store.ts
src/pg/brc20/types.ts
tests/brc20.test.ts
tests/helpers.ts

Add a `brc20_counts_by_address_event_type` table that tracks activity count per address so we can optimize paginated results on `/brc-20/activity?address=` endpoint calls.
Also, fix a BRC-20 `transfer_send` rollback issue when it was a self-transfer

fix: keep count of brc-20 activity per address

---

migrations/1695243716885_brc20-events-addresses.ts
src/pg/brc20/brc20-pg-store.ts

This helps us avoid a nested loop in an earlier query caused by an `OR` condition with a `LEFT JOIN` for `transfer_send` operations

fix: save addresses in brc20 events table for faster queries

---

migrations/1695655140203_counts-by-recursion.ts
migrations/1695655140203_counts-by-recursive.ts
src/pg/counts/counts-pg-store.ts
src/pg/counts/helpers.ts
src/pg/counts/types.ts
src/pg/types.ts
tests/inscriptions.test.ts

Also fix rollback count decrease for genesis address
Fixes #236

fix: create table for recursive inscriptions count

---

src/pg/pg-store.ts
src/pg/types.ts
tests/server.test.ts

The postgres.js config casts the postgres `numeric` type as a string when returning it to JS, causing number comparisons to break when trying to determine a inscription's genesis when it is created and transferred in the same block.
This PR simply parses values as `number` before comparing block height and transaction index.

fix: same-block inscription location pointer comparison

---

src/pg/pg-store.ts
tests/brc20.test.ts
tests/cache.test.ts
tests/inscriptions.test.ts
tests/sats.test.ts
tests/server.test.ts
tests/stats.test.ts
tests/status.test.ts

Also ignore blocks that have already been processed

fix: reject blocks that would create blessed inscription gaps

---

migrations/1698897577725_locations-location-index.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/inscriptions.test.ts

Avoid using `LIMIT` and `OFFSET` by keeping a transfer index per each location per block. This allows us to use a `WHERE` condition to filter the page, which will be very performant in super large blocks.
Also avoid the `COUNT(*) OVER()` by calculating the total using this cached column.

fix: keep block transfer index for faster transfers per block

---

.github/workflows/vercel.yml

Closes https://github.com/hirosystems/ordinals-api/issues/103
Related: https://github.com/hirosystems/stacks-blockchain-api/pull/1787
A deploy hook in Vercel will be contacted whenever there's an update to the `master` branch in this repo, which should automate changes to the docs site as docs changes are made here.

docs: trigger docs.hiro.so refresh on commits to master

---

src/api/schemas.ts

Add additional content to the OpenAPI description section to match the Ordinals API Overview page and to improve SEO

update openapi description

---

src/pg/pg-store.ts
tests/ordhook/server.test.ts

fix: transfers for inscriptions created immediately before

---

src/pg/pg-store.ts
tests/api/inscriptions.test.ts

Temporarily turn off filters by `block_hash` and `output` while we work on a migration to handle those cases

fix: optimize base inscriptions query

---

migrations/1718498685557_inscriptions-block-hash.ts
migrations/1718498703916_current-locations-output.ts
src/pg/block-cache.ts
src/pg/pg-store.ts
src/pg/types.ts
tests/api/inscriptions.test.ts

Reestablish filters by block_hash and output that were temporarily disabled

fix: add output to current locations and block_hash to inscriptions
